// 线性-信息反馈
const feedback = [
  'MsYes',
  'MsShut',
  'MsAsterisk',
  'MsWarning',
  'MsNotes',
  'MsProhibit',
  'MsFail',
  'MsEnd',
  'MsOperation',
  'MsAskQuestion',
  'MsReAsk',
  'MsUserManual',
  'MsTrend',
  'MsInfo2',
  'MsComment',
  'MsA123',
  'MsA404',
  'MsNum0',
  'MsNum1',
  'MsNum2',
  'MsNum3',
  'MsNum4',
  'MsNum5',
  'MsNum6',
  'MsNum7',
  'MsNum8',
  'MsNum9',
];
// 线性-方向指示
const direction = [
  'MsArrowLongTop',
  'MsArrowRight',
  'MsArrowDown',
  'MsArrowLeft',
  'MsBackTop',
  'MsArrowUp',
  'MsArrowDownUp',
  'MsArrowLongRight',
  'MsArrowLongLeft',
  'MsVisit',
  'MsPicturePrevious',
  'MsPictureNext',
  'MsArrowTop',
  'MsArrowRightSm',
  'MsArrowDownSm',
  'MsArrowLeftSm',
  'MsArrowDouble',
  'MsArrowDownDouble',
  'MsArrowLeftTop',
  'MsArrowRightTop',
  'MsBack',
  'MsBackReturn',
  'MsMove',
  'MsFullScreen',
  'MsFullScreenCancel',
  'MsFullScreen2',
  'MsFullScreenCancel2',
  'MsArrowUpDown',
  'MsTriangleUpper',
  'MsTriangleRight',
  'MsTriangleLower',
  'MsTriangleLeft',
  'MsPutAway',
  'MsExpandBelow',
  'MsSwitch',
  'MsStepNext',
  'MsStepPrevious',
  'MsChange2',
  'MsBackups',
  'MsShareSeparate',
  'MsOpenBrowser',
  'MsAddition',
  'MsReduce',
  'MsStageNext',
  'MsSwitchLeftRight',
  'MsSwitchUpDown',
  'MsExtendLeftRight',
  'MsExpandUpDown',
  'MsDragLeftRight',
  'MsLineHeight',
  'MsLineBreakRight',
  'MsLineBreakLeft',
  'MsImport',
  'MsExport',
  'MsDataAscend',
  'MsDescending',
];
// 线性-行动操作
const action = [
  'MsSelect',
  'MsPointer',
  'MsCollection',
  'MsHeart',
  'MsGood',
  'MsBad',
  'MsGuide',
  'MsNotice',
  'MsSee',
  'MsSeeOff',
  'MsCopy',
  'MsCopy2',
  'MsSave',
  'MsFixed',
  'MsSuspend',
  'MsStartUp',
  'MsContinue',
  'MsRestart',
  'MsClose',
  'MsRefresh',
  'MsReset',
  'MsAddGrow',
  'MsCancel',
  'MsEnlarge',
  'MsNarrow',
  'MsSynchronization',
  'MsInquiry',
  'MsMoreHorizontal',
  'MsMoreVertical',
  'MsDrag',
  'MsLoose',
  'MsList',
  'MsBatchProcessing',
  'MsWarningEdit',
  'MsMenu',
  'MsExpandRight',
  'MsExpandLeft',
  'MsSetup',
  'MsTool',
  'MsAdd',
  'MsDelete',
  'MsClean',
  'MsLink',
  'MsEnclosure',
  'MsLogo',
  'MsSubmit',
  'MsDownloadRound',
  'MsUploadImage',
  'MsDownloadImage',
  'MsMoveUp',
  'MsMoveDown',
  'MsUpload',
  'MsDownloadCloud',
  'MsUploadRound',
  'MsDownload',
  'MsUploadFille',
  'MsDownloadFile',
  'MsInfoImport',
  'MsSignOut',
  'MsMoveGroup',
  'MsRevoke',
  'MsImportDraw',
  'MsMoveMent',
  'MsMoveBack',
  'MsDataError',
  'MsAddIncrease',
  'MsAddTask',
  'MsUpdate',
  'MsAddPeers',
  'MsDownAdd',
  'MsAddCondition',
  'MsFormat',
  'MsPartake',
  'MsReplace',
  'MsBind',
  'MsUnbind',
  'MsEdit',
  'MsDataEditing',
  'MsCreateTask',
  'MsRelease',
  'MsFileManage',
  'MsSubFolder',
  'MsCancelAssociation',
  'MsScreen',
  'MsNewQuery',
  'MsThesaurus',
  'MsChoice',
  'MsDiscard',
  'MsCaseReview',
  'MsCaseHanding',
  'MsCloudBuilding',
];

// 线性-内容展示
const content = [
  'MsHome',
  'MsSourceMaterial',
  'MsRisk',
  'MsEarlyWarning',
  'MsAlarmHistory',
  'MsVoiceMonitor',
  'MsPassword',
  'MsLock',
  'MsFreeze',
  'MsLabelManage',
  'MsLabel',
  'MsTest',
  'MsFilter',
  'MsShortMessage',
  'MsCalling',
  'MsTellHistory',
  'MsContacts',
  'MsVerificationCode',
  'MsChat',
  'MsWeiXin',
  'MsConversation',
  'MsConsult',
  'MsSound',
  'MsVoice',
  'MsVideo',
  'MsVideotape',
  'MsMonitor',
  'MsCamera',
  'MsMedia',
  'MsPhoneNumber',
  'MsVerticalScreen',
  'MsPersonalCenter',
  'MsUserList',
  'MsPersonal',
  'MsCrowdPortrait',
  'MsCrowd',
  'MsAccountDeactivate',
  'MsUserSettings',
  'MsAuthorized',
  'MsAddress',
  'MsMap',
  'MsDynamic',
  'MsApi',
  'MsWifi',
  'MsChangeManage',
  'MsChange',
  'MsConfiguration',
  'MsNode',
  'MsNodeHorizontal',
  'MsNodeVertical',
  'MsNodePortrait',
  'MsFlow',
  'MsDataset',
  'MsDataShare',
  'MsOffLine',
  'MsProductCode',
  'MsRotate90',
  'MsStorage',
  'MsSubFile',
  'MsLog',
  'MsExamine',
  'MsScoring',
  'MsHandler',
  'MsFrozen',
  'MsUnfreeze',
  'MsFeedback',
  'MsSeeFile',
  'MsViewRecords',
  'MsDetail',
  'MsTaskConfig',
  'MsDocument',
  'MsAcceptingCases',
  'MsAapprovalPending',
  'MsDraft',
  'MsForm',
  'MsComputerRoom',
  'MsDataQuality',
  'MsMetadataManage',
  'MsServer',
  'MsTaskInstance',
  'MsClassification',
  'MsMetadata',
  'MsShare',
  'MsMore',
  'MsChip',
  'MsToolPut',
  'MsAbility',
  'MsSpace',
  'MsWorkCase',
  'MsRule',
  'MsFocusing',
  'MsUrge',
  'MsTime',
  'MsHistoricalRecords',
  'MsHistoricalVersions',
  'MsRollBack',
  'MsDevelop',
  'MsDateTime',
  'MsCalendar',
  'MsCatalogLibraryTables',
  'MsTemplate',
  'MsBurialPoint',
  'MsTarget',
  'MsDataCloud',
  'MsJurisdiction',
  'MsDataAnalysis',
  'MsLifeCycle',
  'MsLifecycleCycle',
  'MsRecord',
  'MsDataSecurity',
  'MsVerification',
  'MsSecurity',
  'MsRevokeAuth',
  'MsProjectConfig',
  'MsLineChart',
  'MsDataSheet',
  'MsPlatform',
  'MsDataAccess',
  'MsSystem',
  'MsSystemConfig',
  'MsTaskMonitoring',
  'MsAccountInfo',
  'MsAsset',
  'MsCost',
  'MsTemperature',
  'MsDashboard',
  'MsNetwork',
  'MsOnlineFiling',
  'MsMember',
  'MsTrophy',
  'MsDiff',
  'MsInstructions',
  'MsPartner',
  'MsBill',
  'MsRedEnvelope',
  'MsLegalAffairs',
  'MsSword',
  'MsCoupons',
  'MsVersionManage',
  'MsShoppingCart',
  'MsSeal',
  'MsHot',
  'MsRobot',
  'MsGift',
  'AndroidStudio',
];

// 实底-信息反馈
const realBottomDirection = ['MsPrevious', 'MsNext'];

// 实底-方向指示
const realBottomAction = ['MsAddConditions'];

// 双色
// const multicolor = [
//   "Ms"
// ]

// 多色
const colorful = [
  'MsQQ',
  'MsFriendsLife',
  'MsWeibo',
  'MsWeixin',
  'MsIOS18',
  'MsAndroidStudio',
  'MsH5',
  'MsPhone',
  'MsTxt',
  'MsPPT',
  'MsWord',
  'MsXlsx',
  'MsPdfCom',
  'MsGoldMedal',
  'MsSilverMedal',
  'MsBronzeMedal',
  'MsCode403',
  'MsCode404',
  'MsCode500',
  'MsUploadIcon',
  'MsDownloads',
  'MsSparkleIcon',
  'MsByte',
  'MsImgIcon',
  'MsNoComment',
  'MsNoContent',
  'MsNoInfo',
  'MsNoItem',
  'MsNoNotice',
  'MsFile',
  'MsUnknown',
  'MsVideoIcon',
  'MsVoiceIcon',
];

export const categories = {
  feedback,
  direction: [...direction, ...realBottomDirection],
  action: [...action, ...realBottomAction],
  content: [...content, ...colorful],
};

export const allIconsTexts = [
  ...categories.feedback,
  ...categories.direction,
  ...categories.action,
  ...categories.content,
];

export const categoriesEnum = {
  feedback: '信息反馈',
  direction: '方向指示',
  action: '行动操作',
  content: '内容展示',
};

export default categories;

export type Categories = typeof categories;
export type CategoriesKeys = keyof Categories;
export type CategoriesEnumKeys = (typeof categoriesEnum)[keyof typeof categoriesEnum];
